import Foundation

public struct HostsSyncResult {
    public let changed: Bool
    public let blockedDomains: [String]
}

public final class HostsManager {
    private let paths: Paths
    private let settings: RuntimeSettings

    public init(paths: Paths = Paths(), settings: RuntimeSettings = RuntimeSettings()) {
        self.paths = paths
        self.settings = settings
    }

    public func sync(blockedDomains: [String]) throws -> HostsSyncResult {
        try ensureHostsFileExistsIfNeeded()

        let existingContent = try String(contentsOfFile: paths.hostsFilePath, encoding: .utf8)
        let mergedContent = Self.mergedHostsContent(
            existingContent: existingContent,
            blockedDomains: blockedDomains,
            paths: paths
        )

        let changed = mergedContent != existingContent
        if changed {
            try clearImmutableFlagIfNeeded()
            try Data(mergedContent.utf8).write(to: URL(fileURLWithPath: paths.hostsFilePath), options: .atomic)
            if !paths.isRedirectedRoot {
                try FileManager.default.setAttributes([.posixPermissions: 0o644], ofItemAtPath: paths.hostsFilePath)
            }
            try flushDNSCacheIfNeeded()
        }

        if shouldLockHostsFile(for: blockedDomains) {
            try setImmutableFlagIfNeeded()
        } else {
            try clearImmutableFlagIfNeeded()
        }

        return HostsSyncResult(changed: changed, blockedDomains: blockedDomains)
    }

    public func removeManagedSection() throws {
        try _ = sync(blockedDomains: [])
    }

    public func managedSectionPresent() throws -> Bool {
        guard FileManager.default.fileExists(atPath: paths.hostsFilePath) else {
            return false
        }

        let content = try String(contentsOfFile: paths.hostsFilePath, encoding: .utf8)
        return content.contains(paths.managedStartMarker)
    }

    public func isHostsFileImmutable() -> Bool {
        guard !paths.isRedirectedRoot else { return false }
        guard let result = try? Shell.run("/bin/ls", arguments: ["-ldO", paths.hostsFilePath], allowFailure: true) else {
            return false
        }
        return result.stdout.contains("uchg")
    }

    public static func mergedHostsContent(existingContent: String, blockedDomains: [String], paths: Paths = Paths()) -> String {
        let cleaned = stripManagedSection(existingContent, paths: paths).trimmingCharacters(in: .whitespacesAndNewlines)
        let renderedSection = renderManagedSection(for: blockedDomains, paths: paths)

        if renderedSection.isEmpty {
            return cleaned.isEmpty ? "" : cleaned + "\n"
        }

        if cleaned.isEmpty {
            return renderedSection + "\n"
        }

        return cleaned + "\n\n" + renderedSection + "\n"
    }

    public static func renderManagedSection(for blockedDomains: [String], paths: Paths = Paths()) -> String {
        let uniqueDomains = Array(Set(blockedDomains)).sorted()
        guard !uniqueDomains.isEmpty else { return "" }

        var lines = [String]()
        lines.append(paths.managedStartMarker)
        lines.append("# Generated by steadfast. Edit through the steadfast CLI.")

        for domain in uniqueDomains {
            for hostname in DomainNormalizer.hostnamesToBlock(for: domain) {
                lines.append("127.0.0.1 \(hostname)")
                lines.append("::1 \(hostname)")
            }
        }

        lines.append(paths.managedEndMarker)
        return lines.joined(separator: "\n")
    }

    private static func stripManagedSection(_ content: String, paths: Paths) -> String {
        guard let startRange = content.range(of: paths.managedStartMarker),
              let endRange = content.range(of: paths.managedEndMarker) else {
            return content
        }

        let upperBound = content.index(endRange.upperBound, offsetBy: 0)
        var stripped = content
        stripped.removeSubrange(startRange.lowerBound..<upperBound)
        return stripped.replacingOccurrences(of: "\n\n\n", with: "\n\n")
    }

    private func ensureHostsFileExistsIfNeeded() throws {
        guard paths.isRedirectedRoot, !FileManager.default.fileExists(atPath: paths.hostsFilePath) else {
            return
        }

        let hostsURL = URL(fileURLWithPath: paths.hostsFilePath)
        try FileManager.default.createDirectory(
            at: hostsURL.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        try Data("127.0.0.1 localhost\n".utf8).write(to: hostsURL)
    }

    private func shouldLockHostsFile(for blockedDomains: [String]) -> Bool {
        settings.useImmutableHosts && !paths.isRedirectedRoot && !blockedDomains.isEmpty
    }

    private func clearImmutableFlagIfNeeded() throws {
        guard settings.useImmutableHosts, !paths.isRedirectedRoot else { return }
        _ = try? Shell.run("/usr/bin/chflags", arguments: ["nouchg", paths.hostsFilePath], allowFailure: true)
    }

    private func setImmutableFlagIfNeeded() throws {
        guard settings.useImmutableHosts, !paths.isRedirectedRoot else { return }
        _ = try Shell.run("/usr/bin/chflags", arguments: ["uchg", paths.hostsFilePath])
    }

    private func flushDNSCacheIfNeeded() throws {
        guard !paths.isRedirectedRoot else { return }
        _ = try? Shell.run("/usr/bin/dscacheutil", arguments: ["-flushcache"], allowFailure: true)
        _ = try? Shell.run("/usr/bin/killall", arguments: ["-HUP", "mDNSResponder"], allowFailure: true)
    }
}
